name: BoomBow
depend: [Factions]
author: Alec Petridis
website: http://google.com

main: FireBow

commands:
    boombow:
        description: Enable firebow
    tnt:
        description: Summon tnt
    m:
        description: Send a private message to another player.

version: 0.1
